name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    # Code analysis with SonarCloud
    - name: SonarCloud analysis
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.REACTIONIST }}  
        SONAR_TOKEN: ${{ secrets.6ecf2295f819e72bccdee87614e8f8b9a55c0b50 }}
    
    # Unit tests and building with Maven
    - name: Build with Maven
      run: mvn clean verify
      
    # Creating the .jar file
    - name: Build jar
      run: mvn clean compile assembly:single
    
    # Publishing the .jar file as a build artifact
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: target/*.jar
